### ISSUE TITLE
Error while Lazy load rsync.nvim

### ISSUE THREAD

**Issue by vermouthdky** [OscarCreator/rsync.nvim#115]
Hi, thanks for the great plugin! I have encountered the follow bugs when I try to load rsync.nvim using lazy `Lazy load rsync.nvim`. Are there configurations that I missed? I am using the default config as shown in the readme.

Failed to source `/Users/karen_duane/.local/share/nvim/lazy/rsync.nvim/plug
in/rsync.lua`

vim/_editor.lua:421: nvim_exec2()../Users/karen_duane/.local/share/nvim/laz
y/rsync.nvim/plugin/rsync.lua: Vim(source):E5113: Error while calling lua c
hunk: .../.local/share/nvim/lazy/rsync.nvim/lua/rsync/project.lua:4: module
 'rsync_nvim' not found:
^Ino field package.preload['rsync_nvim']
cache_loader: module rsync_nvim not found
cache_loader_lib: module rsync_nvim not found
^Ino file './rsync_nvim.lua'
^Ino file '/opt/homebrew/share/luajit-2.1/rsync_nvim.lua'
^Ino file '/usr/local/share/lua/5.1/rsync_nvim.lua'
^Ino file '/usr/local/share/lua/5.1/rsync_nvim/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/rsync_nvim.lua'
^Ino file '/opt/homebrew/share/lua/5.1/rsync_nvim/init.lua'
^Ino file './rsync_nvim.so'
^Ino file '/usr/local/lib/lua/5.1/rsync_nvim.so'
^Ino file '/opt/homebrew/lib/lua/5.1/rsync_nvim.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
^I[C]: in function 'require'
^I.../.local/share/nvim/lazy/rsync.nvim/lua/rsync/project.lua:4: in main ch
unk
^I[C]: in function 'require'
^I...ane/.local/share/nvim/lazy/rsync.nvim/lua/rsync/init.lua:5: in main ch
unk
^I[C]: in function 'require'
^I...duane/.local/share/nvim/lazy/rsync.nvim/plugin/rsync.lua:2: in main ch
unk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua:421: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in funct
ion <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in funct
ion 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in funct
ion 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in funct
ion 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:407: in funct
ion 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:342: in funct
ion '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in funct
ion 'load'
^I...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:55: in functi
on 'command'

**Comment by OscarCreator** [comment]
Have you built the shared objects with: `make` ?

**Comment by vermouthdky** [comment]
Thanks for the prompt reply! I have manually built the shared objects and it works!
Just found that lazy.nvim use "build" as the keyword rather than "run".

**Comment by OscarCreator** [comment]
If you want you could add the config for lazy in the README
