### ISSUE TITLE
Make with cargo from rtx and add Port

### ISSUE THREAD

**Issue by lvim-tech** [OscarCreator/rsync.nvim#120]
When I use cargo installed with rtx make, it fails.

.../.local/share/nvim/lazy/rsync.nvim/lua/rsync/project.lua:4: module 'rsync_nvim' not found:
	no field package.preload['rsync_nvim']
	
	
And how add port?

**Comment by lvim-tech** [comment]
I think the configuration file would look cleaner like this

[ssh]
host = "example.com"
port = 2222
user = "your_user"
password = "your_pass"

[remote]
remote_path = "/home/user/path/"

**Comment by OscarCreator** [comment]
The module not found error is just a generic one and means that the shared object hasn't been built. 

Do you get any error when running `make`?

The configuration file you specified is something which I would like to make cleaner (using luals class objects) before adding more features. But you can always send a PR and I will have a look.

**Comment by lvim-tech** [comment]
I manually executed 'make,' and now it works. However, when installing the plugin, it throws an error through lazy-loading.

**Comment by lvim-tech** [comment]
How can I add a port to the host? I tried the following method:
remote_path = "user@host:2222:/home/user/public_html/", but it's not working.

**Comment by OscarCreator** [comment]
Port or password is not currently supported. 

Only the default port (could probably override this in your ssh config).

And you have to setup passwordless authentication (`ssh-copy-id`) for you host

**Comment by OscarCreator** [comment]
> I manually executed 'make,' and now it works. However, when installing the plugin, it throws an error through lazy-loading.

I also use lazy but haven't had this problem. After adding this plugin to lazy it should install right away after entering nvim if you use the config in the README

**Comment by underwoodnoble** [comment]
> How can I add a port to the host? I tried the following method: remote_path = "user@host:2222:/home/user/public_html/", but it's not working. What about a password?

I found that you can use the following command to specify the port:
```toml
remote_path = "-e 'ssh -p 45673' user@host:/path/to/project/"
```
