### ISSUE TITLE
missing "," in README configuration

### ISSUE THREAD

**Issue by WikiLiu** [OscarCreator/rsync.nvim#122]

**Comment by OscarCreator** [comment]
Please elaborate, it's not clear what you mean.

**Comment by WikiLiu** [comment]
In your readme doc：
{
    -- triggers `RsyncUp` when fugitive thinks something might have changed in the repo.
    fugitive_sync = false,
    -- triggers `RsyncUp` when you save a file.
    sync_on_save = true
    -- the path to the project configuration
    project_config_path = ".nvim/rsync.toml"
    -- called when the rsync command exits, provides the exit code and the used command
    on_exit = function(code, command)
    end,
    -- called when the rsync command prints to stderr, provides the data and the used command
    on_stderr = function(data, command)
    end,
}


Whether need insert , to the line end of "project_config_path = ".nvim/rsync.toml""  and "sync_on_save = true"?
Maybe cause lua fault?

**Comment by OscarCreator** [comment]
Yes, seems I missed that.

**Comment by OscarCreator** [comment]
Keeping this open until I have fixed this.
