### ISSUE TITLE
rsync does not synchronize files in gitignore that need to be ignored.

### ISSUE THREAD

**Issue by underwoodnoble** [OscarCreator/rsync.nvim#127]
```toml
remote_path = "remote_path"


#ignorefile_paths = ['.git']
#remote_includes = ["local/"]
```

I have a folder named local, I do not want to push it into server, so I add this folder in .gitignore. But after that, I cannot synchronize my local folder to my remote device.

**Comment by OscarCreator** [comment]
You mean the local folder should not be :RsyncUp? But :RsyncDown should? If so it's exactly what remote_includes does.

**Comment by underwoodnoble** [comment]
Sorry, I may not be clear about my problem, I am using a local mac for development, but the code needs to run on the remote server, so I need to use this plugin to synchronize the code to the remote server, the local code and the remote server's code should be the same. In the meantime, I need to push the code into gitlab, but I don't want to push the folder named `local` to gitlab, so I add the `local` to the gitignore file. Now I find that none of the files in gitignore will be synced to the remote server.

**Comment by OscarCreator** [comment]
By default everything in .gitignore is excluded. If all you want is to sync the local folder to the remote then adding the following should work.
```
remote_includes = ["local"]
```

If you want to sync everything in the .gitignore it **might** work to set `ignorefile_paths` to empty array:
```
ignorefile_paths = []
```

**Comment by underwoodnoble** [comment]
Thank you, the configuration works after I restart the nvim.
