### ISSUE TITLE
Popup for rsync over ssh with password protected key

### ISSUE THREAD

**Issue by Dimfred** [OscarCreator/rsync.nvim#81]
Currently there is no popup and probably only a failed exit code, would be great to forward a popup to the user.
I am not sure whether this is possible am not deep in the command processing yet.
If there was a callback function which is called when a key is not present in the running ssh agent, the user could open his own popup?

**Comment by OscarCreator** [comment]
The preferred approach is to use password less authentication. Are you unable to do that?

**Comment by Dimfred** [comment]
I could be able but my keys are sensetive and don't want to compromise security. But i have an Autocmd / check which is just called before each sync cmd which checks the ssh-agent and uses an external ui to enter the pw if necessary
